const R = (await import(process.env.RAPIER || "@dimforge/rapier3d-compat")).default;
import { ScrewSim, DEFAULTS, autoFillPartial, mixShape } from "../src/sim.js";
import { builtinShape, BINS } from "../src/parts.js";
import { jarPool, JAR_DEFAULT } from "../src/sizes.js";
await R.init();
const cfg = JSON.parse(process.argv[2] || "{}");
Math.random = (() => { let s = 12345; return () => (s = (s * 16807) % 2147483647) / 2147483647; })();
const pool = jarPool(JAR_DEFAULT);
const shape = mixShape(pool.map(e => builtinShape(R, e.part, e.dims)));
const b = BINS.find(x => x.id === "hf8-small");
const sim = new ScrewSim(R, { ...DEFAULTS, ...cfg, container: { L: b.L, W: b.W, H: b.H, wall: 3 } }, shape);
const t0 = performance.now();
const g = autoFillPartial(sim, 700); let r;
while (!(r = g.next()).done) for (let i = 0; i < Math.round(0.02 / sim.dt); i++) sim.step();
const fill = (performance.now() - t0) / 1000;
sim.world.profilerEnabled = true;
const keys = ["timingStep","timingCollisionDetection","timingBroadPhase","timingNarrowPhase","timingSolver","timingVelocityAssembly","timingVelocityResolution","timingCcd","timingIslandConstruction","timingUserChanges"];
const acc = Object.fromEntries(keys.map(k => [k, 0]));
const run = (n) => { for (const k of keys) acc[k] = 0; for (let i = 0; i < n; i++) { sim.step(); for (const k of keys) acc[k] += sim.world[k](); } return keys.map(k => k.replace("timing","") + " " + (acc[k] / n).toFixed(2)).join(", "); };
const sleeping = () => sim.screws.filter(s => s.body.isSleeping()).length;
console.log(JSON.stringify(cfg), process.env.RAPIER ? "simd" : "std", "frozen", sim.frozen, "fill", fill.toFixed(1) + "s", "inside", sim.countInside(), "time", sim.time.toFixed(1));
console.log(" settled:", run(300), "| sleeping", sleeping(), "/", sim.screws.length);
for (let i = 0; i < 2000; i++) sim.step();
console.log(" +4s:", run(100), "| sleeping", sleeping(), "/", sim.screws.length);
let contacts = 0; sim.world.narrowPhase.contactPairsWith ? 0 : 0;
